import type { Metadata } from 'next'
import Phase3AdminLayoutWrapper from '@/components/phase-3-admin/common-components/Phase3AdminLayoutWrapper'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className="font-main overflow-x-hidden">
			<Phase3AdminLayoutWrapper>{children}</Phase3AdminLayoutWrapper>
		</div>
	)
}
